/*
 * File: app/view/MyViewport1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport1', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    collapseMode: 'mini',
                    region: 'west',
                    width: 221,
                    autoScroll: true,
                    resizable: true,
                    collapseDirection: 'left',
                    collapseFirst: false,
                    collapsible: false,
                    title: 'My Tree Panel',
                    titleCollapse: true,
                    store: 'MyTreeStore',
                    displayField: 'name',
                    viewConfig: {

                    },
                    listeners: {
                        render: {
                            fn: me.onTreepanelRender,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'toolbar',
                    region: 'north',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                Ext.create('MyApp.view.MyWindow').show();
                            },
                            text: 'MyButton'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            closable: true,
                            title: 'Tab 1'
                        },
                        {
                            xtype: 'panel',
                            closable: true,
                            title: 'Tab 2'
                        },
                        {
                            xtype: 'panel',
                            closable: true,
                            title: 'Tab 3'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onTreepanelRender: function(component, eOpts) {
        Ext.getStore('MyTreeStore').load()
    }

});